In [35]:
import numpy as np


In [4]:
values=[[53.3438, 53.3438, 53.3438, 53.3438, 53.5938, 54.0000, 54.2500, 54.3438,
         54.3125, 54.1250, 53.7188, 52.9062, 52.3750, 52.4688, 52.4688, 52.3750,
         52.1250, 51.7188, 51.2500, 50.7812, 50.3438, 49.9688, 49.5625, 49.1875,
         48.7188, 48.2500, 47.6875, 47.2188, 46.5625, 45.8750, 45.0938, 44.3125,
         43.2500, 42.2812, 41.3125, 39.9062, 38.5625, 37.0000, 35.7188, 33.8438,
         32.0625, 29.9844, 27.8125, 26.1562, 24.0938, 22.3906, 21.5000, 20.2188,
         18.7656, 16.4844, 14.8359, 13.7812, 12.3281, 12.0703, 11.3203, 11.1797,
         10.4219, 11.0000,  9.0391,  9.0547,  9.0625,  9.0469,  9.0312,  9.0234,
          9.0078,  8.9844,  8.9688,  8.9609,  8.9453,  8.9375,  8.9297,  8.9219,
          8.9141,  8.9062,  8.9062,  8.8984,  8.8906,  8.8828,  8.8750,  8.8672,
          8.8672,  8.8594,  8.8594,  8.8516,  8.8516,  8.8438,  8.8438,  8.8359,
          8.8359,  8.8359,  8.8281,  8.8203,  8.8203,  8.8125,  8.8125,  8.8047,
          8.8047,  8.7969,  8.7969,  8.7969,  8.7969,  8.7891,  8.7891,  8.7891,
          8.7891,  8.7812,  8.7812,  8.7812,  8.7812,  8.7812,  8.7812,  8.7734,
          8.7812,  8.7734,  8.7734,  8.7734,  8.7656,  8.7656,  8.7656,  8.7656,
          8.7578,  8.7578,  8.7578,  8.7578,  8.7578,  8.7578,  8.7500,  8.7500,
          8.7500,  8.7422,  8.7500,  8.7422,  8.7422,  8.7422,  8.7422,  8.7422,
          8.7422,  8.7344,  8.7344,  8.7344,  8.7344,  8.7344,  8.7344,  8.7344,
          8.7266,  8.7266,  8.7266,  8.7266,  8.7266,  8.7188,  8.7188,  8.7188,
          8.7188,  8.7188,  8.7188,  8.7188,  8.7188,  8.7109,  8.7109,  8.7109,
          8.7031,  8.7031,  8.7031,  8.7031,  8.7031,  8.7031,  8.7031,  8.7031,
          8.6953,  8.6953,  8.7031,  8.7031,  8.6953,  8.6953,  8.6953,  8.6953,
          8.6953,  8.6953,  8.6953,  8.6953,  8.6875,  8.6953,  8.6875,  8.6875,
          8.6875,  8.6875,  8.6875,  8.6797,  8.6875,  8.6797,  8.6797,  8.6875,
          8.6875,  8.6797,  8.6797,  8.6797,  8.6797,  8.6797,  8.6719,  8.6719,
          8.6641,  8.6719,  8.6719,  8.6719,  8.6719,  8.6719,  8.6641,  8.6641,
          8.6641,  8.6641,  8.6641,  8.6562,  8.6562,  8.6562,  8.6562,  8.6562,
          8.6562,  8.6562,  8.6562,  8.6562,  8.6562,  8.6562,  8.6562,  8.6562,
          8.6484,  8.6562,  8.6484,  8.6484,  8.6484,  8.6484,  8.6406,  8.6406,
           8.6406,  8.6406,  8.6406,  8.6406,  8.6406,  8.6328,  8.6328,  8.6328,
          8.6328,  8.6406,  8.6328,  8.6328,  8.6328,  8.6328,  8.6328,  8.6328,
          8.6328,  8.6328,  8.6328,  8.6250,  8.6328,  8.6250,  8.6250,  8.6172,
          8.6250,  8.6172,  8.6172,  8.6172,  8.6172]]

indices=[[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0, 1095, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015]]

import torch


In [5]:
# convert to torch tensors
values = torch.tensor(values)
indices = torch.tensor(indices)
values

tensor([[53.3438, 53.3438, 53.3438, 53.3438, 53.5938, 54.0000, 54.2500, 54.3438,
         54.3125, 54.1250, 53.7188, 52.9062, 52.3750, 52.4688, 52.4688, 52.3750,
         52.1250, 51.7188, 51.2500, 50.7812, 50.3438, 49.9688, 49.5625, 49.1875,
         48.7188, 48.2500, 47.6875, 47.2188, 46.5625, 45.8750, 45.0938, 44.3125,
         43.2500, 42.2812, 41.3125, 39.9062, 38.5625, 37.0000, 35.7188, 33.8438,
         32.0625, 29.9844, 27.8125, 26.1562, 24.0938, 22.3906, 21.5000, 20.2188,
         18.7656, 16.4844, 14.8359, 13.7812, 12.3281, 12.0703, 11.3203, 11.1797,
         10.4219, 11.0000,  9.0391,  9.0547,  9.0625,  9.0469,  9.0312,  9.0234,
          9.0078,  8.9844,  8.9688,  8.9609,  8.9453,  8.9375,  8.9297,  8.9219,
          8.9141,  8.9062,  8.9062,  8.8984,  8.8906,  8.8828,  8.8750,  8.8672,
          8.8672,  8.8594,  8.8594,  8.8516,  8.8516,  8.8438,  8.8438,  8.8359,
          8.8359,  8.8359,  8.8281,  8.8203,  8.8203,  8.8125,  8.8125,  8.8047,
          8.8047,  8.7969,  

In [6]:
output = {
    "predictions": list(),
    "sequences": list(),
    "repeats": list(),
    "repetitions": list(),
}

In [18]:
sequences = [[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0, 1095, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015,
         1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015, 1015]]

print(len(sequences[0]))
count = 0
for i in sequences[0]:
    if i != 0:
        count += 1
print(count)
# 0 - <pad>
# 1015 - 'the'
# 1095 - 'that'
# decode the sequence into string using simple mapping
mapping = {0: "<pad>", 1015: "the", 1095: "that"}
decoded = "".join([mapping[i] for i in sequences[0]])
print(decoded)

sequences = torch.tensor(sequences)

output["repetitions"] = sequences.clone()
output["sequences"] = sequences.clone()

262
205
<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>thatthethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethethe


In [22]:
# creating a sliding window of size 15 for each word in the sequence
def batch(l, b=15):
    subs = []
    for i in range(len(l) - b):
        subs.append(l[i : i + b])
    return subs

# create a incresing sized window for each word in the sequence starting from 10, 11, 12, 13, 14, 15, ...
def subdiv(l, b=10):
    subs = []
    for i in range(len(l) - b):
        subs.append(l[: i + b])  
    return subs

In [24]:
b = 0
mask = indices[b] != 0
mask

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, 

In [25]:
N = mask.sum().item()
N

205

In [31]:
len(values[0]), values[0]

(261,
 tensor([53.3438, 53.3438, 53.3438, 53.3438, 53.5938, 54.0000, 54.2500, 54.3438,
         54.3125, 54.1250, 53.7188, 52.9062, 52.3750, 52.4688, 52.4688, 52.3750,
         52.1250, 51.7188, 51.2500, 50.7812, 50.3438, 49.9688, 49.5625, 49.1875,
         48.7188, 48.2500, 47.6875, 47.2188, 46.5625, 45.8750, 45.0938, 44.3125,
         43.2500, 42.2812, 41.3125, 39.9062, 38.5625, 37.0000, 35.7188, 33.8438,
         32.0625, 29.9844, 27.8125, 26.1562, 24.0938, 22.3906, 21.5000, 20.2188,
         18.7656, 16.4844, 14.8359, 13.7812, 12.3281, 12.0703, 11.3203, 11.1797,
         10.4219, 11.0000,  9.0391,  9.0547,  9.0625,  9.0469,  9.0312,  9.0234,
          9.0078,  8.9844,  8.9688,  8.9609,  8.9453,  8.9375,  8.9297,  8.9219,
          8.9141,  8.9062,  8.9062,  8.8984,  8.8906,  8.8828,  8.8750,  8.8672,
          8.8672,  8.8594,  8.8594,  8.8516,  8.8516,  8.8438,  8.8438,  8.8359,
          8.8359,  8.8359,  8.8281,  8.8203,  8.8203,  8.8125,  8.8125,  8.8047,
          8.8047,  8.7

In [30]:
len(values[b, mask].float().numpy()), values[b, mask].float().numpy()

(205,
 array([10.4219, 11.    ,  9.0391,  9.0547,  9.0625,  9.0469,  9.0312,
         9.0234,  9.0078,  8.9844,  8.9688,  8.9609,  8.9453,  8.9375,
         8.9297,  8.9219,  8.9141,  8.9062,  8.9062,  8.8984,  8.8906,
         8.8828,  8.875 ,  8.8672,  8.8672,  8.8594,  8.8594,  8.8516,
         8.8516,  8.8438,  8.8438,  8.8359,  8.8359,  8.8359,  8.8281,
         8.8203,  8.8203,  8.8125,  8.8125,  8.8047,  8.8047,  8.7969,
         8.7969,  8.7969,  8.7969,  8.7891,  8.7891,  8.7891,  8.7891,
         8.7812,  8.7812,  8.7812,  8.7812,  8.7812,  8.7812,  8.7734,
         8.7812,  8.7734,  8.7734,  8.7734,  8.7656,  8.7656,  8.7656,
         8.7656,  8.7578,  8.7578,  8.7578,  8.7578,  8.7578,  8.7578,
         8.75  ,  8.75  ,  8.75  ,  8.7422,  8.75  ,  8.7422,  8.7422,
         8.7422,  8.7422,  8.7422,  8.7422,  8.7344,  8.7344,  8.7344,
         8.7344,  8.7344,  8.7344,  8.7344,  8.7266,  8.7266,  8.7266,
         8.7266,  8.7266,  8.7188,  8.7188,  8.7188,  8.7188,  8.7188,


In [33]:
len(batch(values[b, mask].float().numpy())), len(batch(values[b, mask].float().numpy())[0]) # number of windows, window size

(190, 15)

In [36]:
len(np.array([np.var(s) / len(s) for s in batch(values[b, mask].float().numpy())]))

190

In [40]:
var = np.array([np.var(s) / len(s) for s in batch(values[b, mask].float().numpy())])
sub_window = subdiv(var[::-1])
len(sub_window), len(sub_window[0]), len(sub_window[1]), len(sub_window[2])

(180, 10, 11, 12)

In [48]:
varvar = np.array([np.var(v) for v in subdiv(var[::-1])][::-1])
varvar, len(varvar)

(array([1.49106663e-06, 8.68434604e-10, 7.37519869e-10, 5.79362998e-10,
        4.31697938e-10, 3.20826187e-10, 2.38468968e-10, 1.77035380e-10,
        1.36390165e-10, 1.09690894e-10, 9.03347973e-11, 7.44695133e-11,
        6.30349413e-11, 5.30933661e-11, 4.51364130e-11, 3.83445078e-11,
        3.29323591e-11, 2.81580390e-11, 2.41182814e-11, 2.15534090e-11,
        1.97618281e-11, 1.82591324e-11, 1.70450801e-11, 1.57469664e-11,
        1.43684879e-11, 1.28998762e-11, 1.13449131e-11, 9.69346889e-12,
        7.94938535e-12, 6.47570915e-12, 5.17469371e-12, 4.02627030e-12,
        2.95939317e-12, 2.17033355e-12, 1.76685898e-12, 1.47712783e-12,
        1.24008968e-12, 1.11123699e-12, 1.02645284e-12, 9.97757212e-13,
        9.85665285e-13, 9.79158594e-13, 9.78442753e-13, 9.77635250e-13,
        9.80757552e-13, 9.87532995e-13, 9.90810365e-13, 9.90090815e-13,
        9.89374812e-13, 9.92787739e-13, 9.79204077e-13, 9.45909352e-13,
        8.99454321e-13, 8.51525680e-13, 8.14525410e-13, 7.968381

In [43]:
indices[b] == 6

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [50]:
small_var= np.where(varvar < 0.045)[0]
small_var, len(small_var) # in our case all are var are less than 0.045

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [51]:
np.diff(small_var) # out[i] = a[i+1] - a[i] 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [52]:
np.diff(small_var) < 2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [53]:
max(small_var[0], 1)

1

In [54]:
max(small_var[0], 1) * 1.08 + 120

121.08

- if the number of tokens <= 23  `No repeatation`
- if the eos token is present in the sequence `No repeatation`


In [23]:
for b in range(1):
    mask = indices[b] != 0
    N = mask.sum().item()
    var = np.array([np.var(s) / len(s) for s in batch(values[b, mask].float().numpy())])

    if len(var) < 10: # since window size is 15, hence if number of tokens <= 23, then no repetitions 
        output["repeats"].append(None)
        continue
    if (
        indices[b] == 6  # if any of the word is eos and (the number of mask tokens + eos token) is less than total number of tokens
    ).any() and N + 1 < indices.shape[1]: 
        # there is an end to the generation, likely no repetitions
        output["repeats"].append(None)
        continue
    
    varvar = np.array([np.var(v) for v in subdiv(var[::-1])][::-1])
    minlen = 120
    small_var = np.where(varvar < 0.045)[0] # returns the indices of the varvar array where the value is less than 0.045
    if len(small_var) > 1:
        if np.all(np.diff(small_var) < 2):
            idx = int(min(max(small_var[0], 1) * 1.08 + minlen, 4095))
            if idx / N > 0.9:  # at most last bit   # repeatation in the last 10% tokens of the sequence
                output["repeats"].append(None)
                continue
            elif small_var[0] < 30:
                idx = 0
            print("Found repetitions in sample %i" % b)
            output["repeats"].append(idx)
            output["sequences"][b, idx:] = 0
            output["repetitions"][b, :idx] = 0
        else:
            output["repeats"].append(None)
    else:
        output["repeats"].append(None)

[2.34289865e-02 1.68384115e-02 1.70246434e-04 1.83792210e-04
 1.76250500e-04 1.52717220e-04 1.31719947e-04 1.13885275e-04
 9.32893871e-05 7.63590991e-05 6.54831373e-05 5.93635758e-05
 5.09066934e-05 4.74252854e-05 4.26404295e-05 3.94387404e-05
 3.54401845e-05 3.32714252e-05 3.06966443e-05 2.51932050e-05
 2.16353122e-05 2.00229736e-05 1.82969670e-05 1.85895323e-05
 1.88423689e-05 1.91275903e-05 1.93739970e-05 1.96518687e-05
 1.98918472e-05 1.83587409e-05 1.72582824e-05 1.62244280e-05
 1.55754484e-05 1.36285186e-05 1.03836316e-05 9.10222201e-06
 8.39309068e-06 6.77801484e-06 5.91731902e-06 4.47608230e-06
 3.82711757e-06 3.53960568e-06 3.17677016e-06 3.17538919e-06
 2.84676328e-06 2.19089197e-06 2.83709475e-06 3.15605284e-06
 3.14776577e-06 2.81223329e-06 3.78569918e-06 4.43467628e-06
 4.75916507e-06 4.75916459e-06 4.43467579e-06 3.78569918e-06
 4.43467676e-06 3.71359032e-06 3.60542787e-06 4.03807911e-06
 3.17277639e-06 3.60542787e-06 3.71359080e-06 3.49726494e-06
 2.95645101e-06 2.956451